### ISSUE TITLE
No Available Backend Found

### ISSUE THREAD

**Issue by dylie-eth** [mmurray/react-segment-anything#3]
I am receiving the following error when trying to use the component. Because there is no backend, no mask can be saved and nothing happens when bounding boxes are drawn. I tried adding the wasm files to the public/static/js folder but this didn't change anything and I am unsure why this would be necessary. Shouldn't it just pull the wasm files from the onnx-runtimeweb peer dependency?

```
Error: no available backend found. ERR: [wasm] TypeError: e6.shift(...) is not a function, [cpu] Error: previous call to 'initializeWebAssembly()' failed., [xnnpack] Error: previous call to 'initializeWebAssembly()' failed.
    at resolveBackend (backend-impl.js:87:11)
    at async e2.create (inference-session-impl.js:169:15)
```

**Comment by dylie-eth** [comment]
I fixed this issue by downgrading my onnx-runtimeweb version to 1.14.0. I did not realize this was something that was required, although I figured it was a peer dependency. Apparently depending on the onnx-runtimeweb version, different wasm files cannot be used.
